apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.db.port }}
  selector:
    app: {{ .Release.Name }}
    tier: {{ .Release.Name }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.db.image }}:{{ .Values.db.version }}
          resources:
            requests:
              cpu: {{ .Values.dbdeploy.reqcpu }}
              memory: {{ .Values.dbdeploy.reqmem}}
            limits:
              cpu: {{ .Values.dbdeploy.limcpu }}
              memory: {{ .Values.dbdeploy.limem }}
          env:
            - name: {{ .Value.dbdeploy.passwdRootEnvName }}
              value: {{ .Value.dbdeploy.passwdRootEnvValue }}
            - name: {{ .Value.dbdeploy.dbNameEnvName }}
              value: {{ .Value.dbdeploy.dbNameEnvValue }}
            - name: {{ .Value.dbdeploy.dbUserEnvName }}
              value: {{ .Value.dbdeploy.dbUserEnvValue}}
            - name: {{ .Value.dbdeploy.passwdDbEnvName }}
              value: {{ .Value.dbdeploy.passwdDbEnvValue }}
          ports:
            - containerPort: {{ .Values.db.por }}
          volumeMounts:
            - name: {{ .Release.Name }}-persistent-storage
              mountPath: {{ .Value.dbdeploy.volumeMountPath }}
      volumes:
        - name: {{ .Release.Name }}-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.dbhpa.MinRep }}
  maxReplicas: {{ .Values.dbhpa.MaxRep }}
  metrics:
    - type: {{ .Values.dbhpa.MetricsType }}
      resource:
        name: {{ .Value.dbhpa.MetricsResourceCpuName }}
        target:
          type: {{ .Values.dbhpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.dbhpa.CpuAverage }}
    - type: {{ .Values.dbhpa.MetricsType }}
      resource:
        name: {{ .Values.dbhpa.MetricsResourceMemName }}
        target:
          type: {{ .Values.dbhpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.dbhpa.MemAverage }}