apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.wp.port}}
  selector:
    app: {{ .Release.Name }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.wp.tier}}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: {{ .Values.wp.strategyType }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.wp.tier}}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.wp.image }}:{{ .Values.wp.imageVersion }}
          ports:
            - containerPort: {{ .Values.wp.port}}
          env:
            - name: {{ .Values.wp.envDbHostName }}
              value: {{ .Release.Name }}-service
            - name: {{ .Values.wp.envDbName }}
              value: {{ .Value.dbdeploy.passwdRootEnvValue }}
            - name: {{ .Values.wp.envDbUser }}
              value: {{ .Value.dbdeploy.dbUserEnvName }}
            - name: {{ .Values.wp.envDbPasswd }}
              value: {{ .Value.dbdeploy.passwdDbEnvValue }}
          resources:
            requests:
              memory: {{ .Values.wp.reqmem}}
              cpu: {{ .Values.wp.reqcpu }}
            limits:
              memory: {{ .Values.wp.limmem }}
              cpu: {{ .Values.wp.limcpu }}
          volumeMounts:
          - name: {{ .Release.Name }}-persistent-volume
            mountPath: {{ .Values.wp.volumeMountPath }}
      volumes:
      - name: {{ .Release.Name }}-persistent-volume
        persistentVolumeClaim:
          claimName: wp-pvc
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.wphpa.MinRep }}
  maxReplicas: {{ .Values.wphpa.MaxRep }}
  metrics:
    - type: {{ .Values.wphpa.MetricsType }}
      resource:
        name: {{ .Value.wphpa.MetricsResourceCpuName }}
        target:
          type: {{ .Values.wphpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.wphpa.CpuAverage }}
    - type: {{ .Values.wphpa.MetricsType }}
      resource:
        name: {{ .Values.wphpa.MetricsResourceMemName }}
        target:
          type: {{ .Values.wphpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.wphpa.MemAverage }}