version: "3"
services:
    apache:
        build: ./Debian
        ports:
            - 8082:80
        volumes:
            - ./opt/www.test.com:/var/www/html
            - ./opt/logs:/var/log/apache2/
        depends_on:
            - php

    nginx:
        build: ./Centos
        ports:
            - 8080:80
        volumes:
            - ./opt/www.test.com:/var/www/html
            - ./cfg/nginx.conf:/etc/nginx/nginx.conf
            - ./opt/logs:/var/log/nginx/
        depends_on:
            - apache
    php:
        image: php:7.2-fpm
        volumes:
            - ./opt/www.test.com:/var/www/html
            
            
