apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=   # base64-encoded value of "admin"
  DB_PASSWORD: cGFzc3dvcmQ=   # base64-encoded value of "password"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: mysecret
  restartPolicy: Never