
namespace: dev



db:
  name: mysql
  port: 3306
  image: mariadb
  version: ""

dbdeploy:
  passwdRootEnvName: MARIADB_ROOT_PASSWORD
  passwdRootEnvValue: "111111aA"
  dbNameEnvName: MARIADB_DATABASE
  dbNameEnvValue: wordpress
  dbUserEnvName: MARIADB_USER
  dbUserEnvValue: wordpress
  passwdDbEnvName: MARIADB_PASSWORD
  passwdDbEnvValue: "11111111"
  reqcpu: "100m"
  limcpu: "200m"
  reqmem: "100Mi"
  limmem: "200Mi"
  volumeMountPath: /var/lib/mysql
  #PersistentVolumeClaimName: db-pvc


dbhpa:
  MinRep: 1
  MaxRep: 3
  MetricsType: Resource
  MetricsResourceCpuName: cpu
  MetricsResourceMemName: memory
  MetricsResourceTargetType: Utilization
  CpuAverage: 70
  MemAverage: 70


wp:
  tier: frontend
  port: 80
  strategyType: Recreate
  image: wordpress
  imageVersion: 5.9.2-php8.0
  envDbHostName: WORDPRESS_DB_HOST
  envDbName: WORDPRESS_DB_NAME
  envDbUser: WORDPRESS_DB_USER
  envDbPasswd: WORDPRESS_DB_PASSWORD
  reqcpu: "100m"
  limcpu: "200m"
  reqmem: "100Mi"
  limmem: "200Mi"
  volumeMountPath: /var/www/html
  #PersistentVolumeClaimName: wp-pvc

wphpa:
  MinRep: 1
  MaxRep: 3
  MetricsType: Resource
  MetricsResourceCpuName: cpu
  MetricsResourceMemName: memory
  MetricsResourceTargetType: Utilization
  CpuAverage: 70
  MemAverage: 70

networkpolicy:
  name: np-wp
  policyType: Ingress
  protocol: TCP
  port: 3306