apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "172.31.24.88" #"$DOCKER_HOST_IP"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
nodes:
- role: control-plane
- role: worker
  labels:
    type: edge
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 82
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 83
    listenAddress: "0.0.0.0"
    protocol: TCP

