mysql:
  image: mysql:5.7
  container_name: mysql_db
  environment:
    MYSQL_DATABASE: 'mysql'
#    We cannot set user as 'root' if mysql is below version of 5.x
    MYSQL_ROOT_PASSWORD: '12345678'
  ports:
    - "3308:3306"
  volumes:
 #   - ./mysql_conf.sql:/etc/mysql/conf.d
    - ./data/logs:/logs
    - ./mysql_data:/var/lib/mysql