---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.db.port }}
  selector:
    app: {{ .Release.Name }}
    tier: {{ .Values.db.name }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.db.image }}
          resources:
            requests:
              cpu: {{ .Values.dbdeploy.reqcpu }}
              memory: {{ .Values.dbdeploy.reqmem }}
            limits:
              cpu: {{ .Values.dbdeploy.limcpu }}
              memory: {{ .Values.dbdeploy.limmem }}
          env:
          - name: {{ .Values.dbdeploy.passwdRootEnvName }}
            value: {{ .Values.dbdeploy.passwdRootEnvValue }}
          - name: {{ .Values.dbdeploy.dbNameEnvName }}
            value: {{ .Values.dbdeploy.dbNameEnvValue }}
          - name: {{ .Values.dbdeploy.dbUserEnvName }}
            value: {{ .Values.dbdeploy.dbUserEnvValue }}
          - name: {{ .Values.dbdeploy.passwdDbEnvName }}
            valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.wp.envSecretKeyRefKey }}
          ports:
            - containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: {{ .Release.Name }}-persistent-storage
              mountPath: {{ .Values.dbdeploy.volumeMountPath }}
      volumes:
        - name: {{ .Release.Name }}-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.db.name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.db.name }}
  minReplicas: {{ .Values.dbhpa.MinRep }}
  maxReplicas: {{ .Values.dbhpa.MaxRep }}
  metrics:
    - type: {{ .Values.dbhpa.MetricsType }}
      resource:
        name: {{ .Values.dbhpa.MetricsResourceCpuName }}
        target:
          type: {{ .Values.dbhpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.dbhpa.CpuAverage }}
    - type: {{ .Values.dbhpa.MetricsType }}
      resource:
        name: {{ .Values.dbhpa.MetricsResourceMemName }}
        target:
          type: {{ .Values.dbhpa.MetricsResourceTargetType }}
          averageUtilization: {{ .Values.dbhpa.MemAverage }}