version: "3"
services:
    apache:
        build: ./Centos
        volumes:
            - ./index:/var/www/html
        depends_on:
            - php

    nginx:
        build: ./Debian
        ports:
            - 8080:80
        volumes:
            - ./index:/var/www/html
            - ./cfg/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - apache
    php:
        image: php:7.2-fpm
        volumes:
            - ./index:/var/www/html
