
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName:  ""
  hostPath:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker2
---

apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: dev
  labels:
    app: wp-pvc
spec:
  storageClassName:  ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dev
  labels:
    app: db-pvc
spec:
  storageClassName:  ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi